-- Table creation schema for  CUSTOMER
CREATE TABLE CUSTOMER
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255)
);


-- Table creation schema for TRANSACTION
CREATE TABLE PURCHASES
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    DATE        DATE           NOT NULL,
    AMOUNT      DECIMAL(10, 2) NOT NULL,
    CUSTOMER_ID BIGINT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID)
);
